### ISSUE TITLE
Error al eliminar una ruta cuando todo fue sastifactorio

### ISSUE THREAD

**Issue by jmatos29** [KalleyBacker/Path-Manager#1]
Al eliminar una ruta aparece el mensaje diciendo que se elimino, y tambien aparece un mensaje mas abajo diciendo que hay un error que no encontro el ID de la ruta.

![Screenshot from 2024-01-08 14-50-34](https://github.com/KalleyBacker/Path-Manager/assets/32989961/b3931ea9-82f9-49bd-baa8-ce493336d479)

**Comment by KalleyBacker** [comment]
El error se produjo porque se proporcionó un parámetro incorrecto a la función "lista. La solución fue comentar la línea. 
![Screenshot from 2024-01-08 15-55-49](https://github.com/KalleyBacker/Path-Manager/assets/84671791/f08f3ca9-16a4-4518-bba5-df624c1999be)

**Comment by jmatos29** [comment]
Exelente!
